name: Flutter CI/CD Pipeline

on:
  pull_request:
    branches:
      - dev

jobs:
  analyze-dev-pull-request:
    name: Analyze on Dev Pull Request
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.2

      # Step 3: Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # Step 3: Run Flutter Analyze
      - name: Analyze Code
        run: flutter analyze

  build-dev-pull-request:
    name: Build on Dev Pull Request
    runs-on: ubuntu-latest
    needs: analyze-dev-pull-request
    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.2
          
      # Step 3: Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # Step 4: Build Flutter Web
      - name: Build Flutter Web
        id: build
        run: flutter build web --debug
