name: Flutter CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  analyze-main-pull-request:
    name: Analyze on main Pull Request
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.2

      # Step 3: Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # Step 3: Run Flutter Analyze
      - name: Analyze Code
        run: flutter analyze

  test-main-pull-request:
    name: Test on main Pull Request
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: analyze-main-pull-request
    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.2
          
      # Step 3: Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # Step 3: Run Flutter Test
      - name: Run Tests
        run: flutter test

  build-main-pull-request:
    name: Build on main Pull Request
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: test-main-pull-request
    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.2
          
      # Step 3: Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # Step 4: Configure GitHub Pages
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      # Step 5: Build Flutter Web
      - name: Build Flutter Web
        id: build
        run: flutter build web --release

      # Step 6: Upload GitHub Pages artifact
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: ./build/web

  build-main-push:
    name: Build on main Push
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.2
          
      # Step 3: Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # Step 4: Configure GitHub Pages
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      # Step 5: Build Flutter Web
      - name: Build Flutter Web
        id: build
        run: flutter build web --release

      # Step 6: Upload GitHub Pages artifact
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: ./build/web
      
  deploy-main-push:
    name: Deploy on main Push
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build-main-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      # Step 1: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
