name: Flutter CI/CD Pipeline

on:
  pull_request:
    branches:
      - qa

jobs:
  analyze-qa-pull-request:
    name: Analyze on QA Pull Request
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.8

      # Step 3: Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # Step 3: Run Flutter Analyze
      - name: Analyze Code
        run: flutter analyze

  test-qa-pull-request:
    name: Test on QA Pull Request
    runs-on: ubuntu-latest
    needs: analyze-qa-pull-request
    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.8
          
      # Step 3: Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # Step 3: Run Flutter Test
      - name: Run Tests
        run: flutter test

  build-qa-pull-request:
    name: Build on QA Pull Request
    runs-on: ubuntu-latest
    needs: test-qa-pull-request
    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.8
          
      # Step 3: Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # Step 4: Build Flutter Web
      - name: Build Flutter Web
        id: build
        run: flutter build web --profile
