name: Flutter CI/CD Pipeline

on:
  pull_request:
    branches:
      - qa

jobs:
  analyze-qa-pull-request:
    name: Analyze in QA Pull Request
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.0

      # Step 3: Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # Step 3: Run Flutter Analyze
      - name: Analyze Code
        run: flutter analyze

  test-qa-pull-request:
    name: Test in QA Pull Request
    runs-on: ubuntu-latest
    needs: analyze-qa-pull-request
    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.0
          
      # Step 3: Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # Step 3: Run Flutter Test
      - name: Run Tests
        run: flutter test

  build-qa-pull-request:
    name: Build in QA Pull Request
    runs-on: ubuntu-latest
    needs: test-qa-pull-request
    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.0
          
      # Step 3: Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # Step 4: Configure GitHub Pages
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      # Step 5: Build Flutter Web
      - name: Build Flutter Web
        id: build
        run: flutter build web --profile

      # Step 6: Upload GitHub Pages artifact
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: ./build/web
